%% Load data files
load('Lux.mat'); %Light intensity along dose-response plot (lux)
load('DRC RPA.mat'); %Relative pupil area values of wildtype rapid dose-response curve
load('Weights.mat'); %Time weighting vector generated by 1s light pulse-chase experiment
Lux=Lux.'; %Transposes Lux vector for later steps
RPA=RPA.'; %Transposes DRC RPA vector for later steps
Values=zeros(957,10000); %Creates matrix which will be filled by model

%%
for y=1:1001 % 'for' loop iterates from y=1 to y=1001
    %% Initial PLR caused by light intensity Lux(y) presented to dark-adapted pupil 
    nRPA=RPA(y); %Extracts relative pupil area (RPA) value at Lux(y) making nRPA for later use
    Weighted=Weights*nRPA; %Weights contribution of initial light across time using 'Weights' vector
    %% Subsequent PLR at times t=2 (1s) to t=957 (956s) taking previous constriction into account when determining retinal intensity
    for t=2:957;
        nIntensity=Lux(y)*(1-max(Weighted(t,1:t-1))); %Calculates new intensity taking PLR into account
        nDiff=abs(Lux-nIntensity); %Finds coordinates of new intensity in 'Lux' vector
        [~,idx]=min(nDiff); %Finds coordinate of new intensity in 'Lux' vector
        nClosest=Lux(idx); %Saves coordinate in nClosest
        nnRPA=RPA(idx); %Determines constriction induced by new retinal intensity and saves it as nnRPA
        Weighted(t:t+30,t)=Weights*nnRPA; % Weights contribution of newly driven PLR across time using 'Weights'
    end
    %% Stores constriction values determined by the model for that time point in 'Values'
    for x=1:957; 
        Values(x,y)=max(Weighted(x,:)); 
    end
end

Values=1-Values; %% Inverts values for visualization. Changes no constriction from 0 to 1